@echo off
mkdir Graphics\Animations
mkdir Graphics\Battlebacks1
mkdir Graphics\Battlebacks2
mkdir Graphics\Battlers
mkdir Graphics\Characters
mkdir Graphics\Faces
mkdir Graphics\Parallaxes
mkdir Graphics\System
mkdir Graphics\Tilesets
mkdir Graphics\Titles1
mkdir Graphics\Titles2
echo Graphical Directories Made
copy /b Copy.png >NUL Graphics\Animations\Attack1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack7.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack8.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack9.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack10.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack11.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Attack12.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Blow1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Blow2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Blow3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Darkness1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Darkness2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Darkness3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Death1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Earth1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Earth2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Earth3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Fire1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Fire2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Fire3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Fire4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Gun1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Gun2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Heal6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Ice1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Ice2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Ice3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Ice4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Ice5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Light7.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Meteor.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Spear1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Spear2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Spear3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special7.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special8.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special9.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special10.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special11.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special12.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special13.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special14.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special15.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special16.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Special17.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\State6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword5.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword6.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword7.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword8.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword9.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Sword10.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Thunder1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Thunder2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Thunder3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Thunder4.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Water1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Water2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Water3.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Wind1.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Wind2.png >NUL
copy /b Copy.png >NUL Graphics\Animations\Wind3.png >NUL
echo Animations Blanked
copy /b Copy.png >NUL Graphics\Battlebacks1\Castle.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Clouds.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Cobblestones1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Cobblestones2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Cobblestones3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Cobblestones4.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Crystal1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Crystal2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Darkspace.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\DecorativeTile.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\DemonCastle.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Demonicworld1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Demonicworld2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Desert.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Dirt1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Dirt2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\DirtCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\DirtField.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Factory1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Factory2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Fort.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Grassland.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\GrassMaze.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\IceCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\IceMaze.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\InBody.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Lava1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Lava2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\LavaCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Meadow.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Paved.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\PoisonSwamp.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Road1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Road2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Road3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\RockCave1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\RockCave2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Ruins1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Ruins2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Ruins3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Sand.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Ship.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Sky.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Snow.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Snowfield.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Stone1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Stone2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Stone3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Tent.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Translucent.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Wasteland.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\WireMesh.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Wood1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks1\Wood2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Brick.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Bridge.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Castle1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Castle2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Castle3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Cliff.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Clouds.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Crystal.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DarkSpace.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DemonCastle1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DemonCastle2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DemonCastle3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DemonicWorld.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Desert.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\DirtCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Factory.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Forest1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Forest2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Fort1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Fort2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Grassland.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\GrassMaze.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\IceCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\IceMaze.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\InBody.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Lava.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\LavaCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Mine.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\PoisonSwamp.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Port.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\RockCave.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Room1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Room2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Room3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Room4.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Ruins.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Sea.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Ship.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Sky.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Snowfield.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Stone1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Stone2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Stone3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Stone4.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Stone5.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Temple.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Tent.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Tower.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Town1.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Town2.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Town3.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Town4.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Town5.png >NUL
copy /b Copy.png >NUL Graphics\Battlebacks2\Wasteland.png >NUL
echo Battlebacks Blanked
copy /b Copy.png >NUL Graphics\Battlers\Angel.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Assassin.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Asura.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Bandit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Bat.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Behemoth.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Captain.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Chimera.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Cleric_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Cleric_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Cockatrice.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Darklord.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Death.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Delf_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Delf_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Demon.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Dragon.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Earthspirit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Evilgod.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Evilking.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Fairy.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Fanatic.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Firespirit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Gargoyle.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Garuda.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Gayzer.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\General.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Ghost.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\God.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Goddess.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Grappler_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Grappler_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Hero_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Hero_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Hornet.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Icelady.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Ifrit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Imp.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Jellyfish.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Kerberos.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Lamia.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Mage.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Mimic.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Minotaur.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Ogre.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Orc.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Paladin_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Paladin_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Plant.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Priest.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Puppet.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Rat.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Rogue.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Sahagin.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Scorpion.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Skeleton.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Slime.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Snake.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Soldier.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Spider.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Succubus.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Swordman.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Thief_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Thief_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Vampire.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Warrior_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Warrior_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Waterspirit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Werewolf.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Willowisp.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Windspirit.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Wizard_f.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Wizard_m.png >NUL
copy /b Copy.png >NUL Graphics\Battlers\Zombie.png >NUL
echo Battelers Blanked
copy /b Copy.png >NUL Graphics\Characters\!$Gate1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!$Gate2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Chest.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Crystal.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Door1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Door2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Door3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Flame.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Hexagram.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Other1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Other2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Other3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Switch1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\!Switch2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\$BigMonster1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\$BigMonster2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\$Coffin.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Actor1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Actor2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Actor3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Actor4.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Actor5.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Animal.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Behavior1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Behavior2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Behavior3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Behavior4.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Damage1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Damage2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Damage3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Damage4.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Evil.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Insane1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Insane2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Monster1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Monster2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Monster3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People1.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People2.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People3.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People4.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People5.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People6.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People7.png >NUL
copy /b Copy.png >NUL Graphics\Characters\People8.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Riding.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Spiritual.png >NUL
copy /b Copy.png >NUL Graphics\Characters\Vehicle.png >NUL
echo Characters Blanked
copy /b Copy.png >NUL Graphics\Faces\Actor1.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Actor2.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Actor3.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Actor4.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Actor5.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Evil.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Monster1.png >NUL
copy /b Copy.png >NUL Graphics\Faces\People1.png >NUL
copy /b Copy.png >NUL Graphics\Faces\People2.png >NUL
copy /b Copy.png >NUL Graphics\Faces\People3.png >NUL
copy /b Copy.png >NUL Graphics\Faces\People4.png >NUL
copy /b Copy.png >NUL Graphics\Faces\Spiritual.png >NUL
echo Faces Blanked
copy /b Copy.png >NUL Graphics\Parallaxes\BlueSky.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\CloudySky1.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\CloudySky2.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\DarkSpace1.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\DarkSpace2.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Mountains1.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Mountains2.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Mountains3.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Mountains4.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Mountains5.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Ocean1.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Ocean2.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\SeaofClouds.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\StarlitSky.png >NUL
copy /b Copy.png >NUL Graphics\Parallaxes\Sunset.png >NUL
echo Paralaxes Blanked
copy /b Copy.png >NUL Graphics\System\Balloon.png >NUL
copy /b Copy.png >NUL Graphics\System\BattleStart.png >NUL
copy /b Copy.png >NUL Graphics\System\GameOver.png >NUL
copy /b Copy.png >NUL Graphics\System\IconSet.png >NUL
copy /b Copy.png >NUL Graphics\System\Shadow.png >NUL
copy /b Copy.png >NUL Graphics\System\Window.png >NUL
echo System Blanked
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_A1.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_A2.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_A3.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_A4.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_A5.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_B.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Dungeon_C.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_A1.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_A2.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_A3.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_A4.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_A5.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_B.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Inside_C.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_A1.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_A2.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_A3.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_A4.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_A5.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_B.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\Outside_C.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\World_A1.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\World_A2.png >NUL
copy /b Copy.png >NUL Graphics\Tilesets\World_B.png >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_A1.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_A2.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_A3.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_A4.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_A5.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_B.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Dungeon_C.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_A1.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_A2.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_A3.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_A4.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_A5.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_B.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Inside_C.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_A1.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_A2.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_A3.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_A4.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_A5.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_B.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\Outside_C.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\World_A1.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\World_A2.txt >NUL
copy /b Copy.txt >NUL Graphics\Tilesets\World_B.txt >NUL
echo Tilesets Blanked
copy /b Copy.png >NUL Graphics\Titles1\Book.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Castle.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\CrossedSwords.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Crystal.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\DemonCastle.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Devil.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Dragon.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Fountain.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Gates.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Hexagram.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Island.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Night.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Plain.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Sword.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Tower1.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Tower2.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Universe.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\Volcano.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\World.png >NUL
copy /b Copy.png >NUL Graphics\Titles1\WorldMap.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Dragons.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Fire.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Forest.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Gargoyles.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Heroes.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Leaves.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Metal.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Mist.png >NUL
copy /b Copy.png >NUL Graphics\Titles2\Mountains.png >NUL
echo Titles Blanked
mkdir Audio\BGM
mkdir Audio\BGS
mkdir Audio\ME
mkdir Audio\SE
echo Audio Directories Made
copy /b Copy.ogg >NUL Audio\BGM\Airship.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle5.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle6.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle7.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle8.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Battle9.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon5.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon6.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon7.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon8.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Dungeon9.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Field1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Field2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Field3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Field4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene5.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Scene6.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Ship.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Theme1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Theme2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Theme3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Theme4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Theme5.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town1.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town2.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town3.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town4.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town5.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town6.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGM\Town7.ogg >NUL
echo BGM Blanked
copy /b Copy.ogg >NUL Audio\BGS\Clock.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Darkness.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Drips.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Fire.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Quake.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Rain.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\River.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Sea.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Storm.ogg >NUL
copy /b Copy.ogg >NUL Audio\BGS\Wind.ogg >NUL
echo BGS Blanked
copy /b Copy.ogg >NUL Audio\ME\Fanfare1.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Fanfare2.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Fanfare3.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Gag.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Gameover1.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Gameover2.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Inn.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Item.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Mystery.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Organ.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Shock.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Victory1.ogg >NUL
copy /b Copy.ogg >NUL Audio\ME\Victory2.ogg >NUL
echo ME Blanked
copy /b Copy.ogg >NUL Audio\SE\Absorb1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Absorb2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Applause1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Applause2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Attack1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Attack2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Attack3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Autodoor.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Barrier.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Battle1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Battle2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Battle3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bell1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bell2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bell3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bite.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blind.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Blow8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Book1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Book2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bow1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bow2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bow3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Bow4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Break.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Breath.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Buzzer1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Buzzer2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cancel1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cancel2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cat.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Chest.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Chicken.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Chime1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Chime2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Close1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Close2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Close3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Coin.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Collapse1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Collapse2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Collapse3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Collapse4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Confuse.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cow.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Crash.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Crossbow.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Crow.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cry1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cry2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cursor1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Cursor2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Damage1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Damage2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Damage3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Damage4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Damage5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Darkness8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Decision1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Decision2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Decision3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Devil1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Devil2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Devil3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Disappointment.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Dive.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Dog.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Down1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Down2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Down3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Down4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Earth9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Equip1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Equip2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Equip3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Evasion1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Evasion2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Explosion7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fall.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fire9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Flash1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Flash2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Flash3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fog1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Fog2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Frog.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Gun1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Gun2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Hammer.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Heal7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Horse.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice10.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Ice11.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Item1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Item2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Item3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Jump1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Jump2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Key.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Knock.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Laser.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Load.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Machine.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Magic7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Miss.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Monster7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Move.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Noise.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Open1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Open2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Open3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Open4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Open5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Paralyze1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Paralyze2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Paralyze3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Parry.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Phone.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Poison.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Pollen.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Powerup.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Push.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Raise1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Raise2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Raise3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Recovery.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Reflection.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Resonance.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Run.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Saint9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sand.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Save.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Scream.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sheep.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Shop.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Shot1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Shot2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Shot3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Silence.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Skill1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Skill2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Skill3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash10.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash11.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Slash12.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sleep.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sound1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sound2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sound3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Stare.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Starlight.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Switch1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Switch2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Switch3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sword1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sword2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sword3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sword4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Sword5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Teleport.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder10.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder11.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Thunder12.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Twine.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Up1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Up2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Up3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Up4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Water6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind1.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind2.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind3.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind4.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind5.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind6.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind7.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind8.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind9.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind10.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wind11.ogg >NUL
copy /b Copy.ogg >NUL Audio\SE\Wolf.ogg >NUL
echo SE Blanked
echo All done! :)
pause